version: '3'
services:
  python_container:
    build:
      context: ./
      args:
        - IMAGE=mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
      target: python_stage
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
