services:
  go_container:
    build:
      context: ../..
      args:
        - IMAGE=mcr.microsoft.com/devcontainers/go:dev-1.22-bookworm
      target: go_stage
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
